//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryAccounting.ModelDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountingInventory
    {
        public int AccountingID { get; set; }
        public int ItemID { get; set; }
        public System.DateTime Accounting { get; set; }
        public int ItemQuanty { get; set; }
        public int WorkerID { get; set; }
    
        public virtual Items Items { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
